import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import ApolloWrapper from "@/lib/ApolloWrapper";
import { ThemeProvider } from "@/components/ThemeProvider";
import ScrollToTop from "@/components/ScrollToTop";
import { UserProvider } from "@/context/UserContext";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AniGO",
  description: "Generated by create next app",
};

async function getUser() {
  const cookieStore = cookies();
  const session = (await cookieStore).get("session")?.value;

  if (!session) return null;

  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000";
  const res = await fetch(`${baseUrl}/api/auth/me`, {
    headers: {
      "Content-Type": "application/json",
      cookie: `session=${session}`,
    },
    cache: "no-store",
  });

  const data = await res.json();
  return data.user;
}


export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const user = await getUser();

  return (
    <html lang="ru" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ScrollToTop />
        <ApolloWrapper>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <UserProvider initialUser={user}>
              <Header />
              {children}
            </UserProvider>
          </ThemeProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
